project:
  type: website

website:
  title: "Ringberg Popgen Workshop 2026"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - popgen_1_heterozygosity.qmd
      - popgen_2_roh.qmd

format:
  html:
    theme: cosmo
    toc: true
