project:
  type: website

website:
  title: "Ringberg Popgen Workshop 2026"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "Popgen 1: Heterozygosity"
        href: popgen_1_heterozygosity.qmd
      - text: "Popgen 2: ROH"
        href: popgen_2_roh.qmd
      - text: "Popgen 3: FST"
        href: popgen_3_drift_fst.qmd
      - text: "Relatedness and Pedigrees (Files)"
        href: relatedness_files.qmd
      - text: "IBD (Script and Files)"
        href: ibd_script_and_files.qmd

format:
  html:
    theme: cosmo
    toc: true
